name: run-ci
on:
  pull_request:
    branches: [ develop ]

jobs:
  check-applications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '18.19.1'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test